# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "njU7F5V2TjHfcSu1Uthr+z3NQiKhIHnPbdTaMhsAq1iOtS00wxMQJFeKhFPuplxn00MfPfBWXXkZwapjVk7q8u+GpXWm8f1W6KXKYS+YbLp1xCl3mw87175FfGXSyLAZ7+0EfySktM0+PNZZTgMiX0nA3VvBlGMGcgAGQC9FNxBTtA1z5y6UA0AvDu0y5ztQLPsSiSIIt7vIYuNFno2mxCXXsOUK/YljhzCQYo3QuSvtHW6UG8VRgmd8VyurqE7FehGqNn9C3BYFWNRxQidnUJlHjUZElrqkiEaXNMAYmUvRrheW0MbsdDFYRW4O5lH+7/IlegmjoKu0G7W7IY0abMYrlYGlseAQ/LH445VTG4mMoR2zn8ww7bzPga3izpAU+aBi7yeLC0bHC2ZMoxeQQgmECEdWpMQai5//tzJ1APvVoZhV9f7eJ/5sUDNxUCnNjYWutgi2pE6aaSVu6do2stbHItFUxsM51LGqRQofbJ6jwza9JZB7uc/K6G6aqx4sIkAKdf9O0ENPh8egqy/rPC9csz5LbinRuwbFEEz/RMaSAz0y1efx6L/SpueN1M5Hz1rFFPyH20g7HWRpN1l6DERCfJllyk6XUDfLi49YgplK573YJ7P3K4r3UrayFgsP6mjOUKHJ+Xodcmb18Tjg4tdVdY3fsVjQ5fSMKnd7RL4="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ctng_binutils2.29.1ctng_cpu_archaarch64ctng_gcc7.5.0ctng_target_platformlinux-aarch64old_ctng_vendorconda_cos7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.29.1ctng_cpu_archaarch64ctng_gcc8.4.0ctng_target_platformlinux-aarch64old_ctng_vendorconda_cos7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.29.1ctng_cpu_archaarch64ctng_gcc9.3.0ctng_target_platformlinux-aarch64old_ctng_vendorconda_cos7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.31.1ctng_cpu_archpowerpc64lectng_gcc7.5.0ctng_target_platformlinux-ppc64leold_ctng_vendorconda_cos7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.31.1ctng_cpu_archpowerpc64lectng_gcc8.4.0ctng_target_platformlinux-ppc64leold_ctng_vendorconda_cos7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.31.1ctng_cpu_archpowerpc64lectng_gcc9.3.0ctng_target_platformlinux-ppc64leold_ctng_vendorconda_cos7target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.31.1ctng_cpu_archx86_64ctng_gcc7.5.0ctng_target_platformlinux-64old_ctng_vendorconda_cos6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.31.1ctng_cpu_archx86_64ctng_gcc8.4.0ctng_target_platformlinux-64old_ctng_vendorconda_cos6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_ctng_binutils2.31.1ctng_cpu_archx86_64ctng_gcc9.3.0ctng_target_platformlinux-64old_ctng_vendorconda_cos6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi