binutils_version:
- '2.40'
c_stdlib:
- sysroot
c_stdlib_version:
- '2.17'
channel_sources:
- conda-forge/label/sysroot-with-crypt,conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- osx-arm64
cross_target_stdlib:
- macosx_deployment_target
cross_target_stdlib_version:
- '11.0'
docker_image:
- quay.io/condaforge/linux-anvil-x86_64:alma9
gcc_maj_ver:
- '14'
gcc_version:
- 14.3.0
libgfortran_soname:
- '5'
libgomp_ver:
- 1.0.0
openmp_ver:
- '4.5'
target_platform:
- linux-aarch64
triplet:
- arm64-apple-darwin
with_conda_specs:
- false
- true
zip_keys:
- - cross_target_stdlib_version
  - cross_target_stdlib
  - triplet
  - cross_target_platform
- - gcc_version
  - gcc_maj_ver
  - libgfortran_soname
