# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-15
  strategy:
    matrix:
      ? osx_64_cross_target_platformlinux-64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_64_cross_target_platformlinux-64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformlinux-64cros_hb2331ffd
      ? osx_64_cross_target_platformlinux-aarch64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_64_cross_target_platformlinux-aarch64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformlinux-aarch6_h3c1d2d65
      ? osx_64_cross_target_platformlinux-ppc64lecross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_64_cross_target_platformlinux-ppc64lecross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformlinux-ppc64l_hf4738459
      ? osx_64_cross_target_platformlinux-riscv64cross_target_stdlibsysrootcross_target_stdlib_version2.39gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_64_cross_target_platformlinux-riscv64cross_target_stdlibsysrootcross_target_stdlib_version2.39gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformlinux-riscv6_hfb3bcdd8
      osx_64_cross_target_platformosx-64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0:
        CONFIG: osx_64_cross_target_platformosx-64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformosx-64cross__h68155d17
      osx_64_cross_target_platformosx-arm64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0:
        CONFIG: osx_64_cross_target_platformosx-arm64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformosx-arm64cro_h803991d4
      ? osx_64_cross_target_platformwin-64cross_target_stdlibm2w64-sysrootcross_target_stdlib_version12gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_64_cross_target_platformwin-64cross_target_stdlibm2w64-sysrootcross_target_stdlib_version12gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_64_cross_target_platformwin-64cross__h716bebef
      ? osx_arm64_cross_target_platformlinux-64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_arm64_cross_target_platformlinux-64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformlinux-64c_h5018df16
      ? osx_arm64_cross_target_platformlinux-aarch64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_arm64_cross_target_platformlinux-aarch64cross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformlinux-aar_hbc45c0e6
      ? osx_arm64_cross_target_platformlinux-ppc64lecross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_arm64_cross_target_platformlinux-ppc64lecross_target_stdlibsysrootcross_target_stdlib_version2.17gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformlinux-ppc_h09418c13
      ? osx_arm64_cross_target_platformlinux-riscv64cross_target_stdlibsysrootcross_target_stdlib_version2.39gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_arm64_cross_target_platformlinux-riscv64cross_target_stdlibsysrootcross_target_stdlib_version2.39gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformlinux-ris_h0960fff6
      osx_arm64_cross_target_platformosx-64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0:
        CONFIG: osx_arm64_cross_target_platformosx-64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformosx-64cro_h4799ba8c
      osx_arm64_cross_target_platformosx-arm64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0:
        CONFIG: osx_arm64_cross_target_platformosx-arm64cross_target_stdlibNonecross_target_stdlib_version0gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformosx-arm64_h1e102690
      ? osx_arm64_cross_target_platformwin-64cross_target_stdlibm2w64-sysrootcross_target_stdlib_version12gcc_maj_ver15gcc_version15.2.0
      : CONFIG: osx_arm64_cross_target_platformwin-64cross_target_stdlibm2w64-sysrootcross_target_stdlib_version12gcc_maj_ver15gcc_version15.2.0
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: osx_arm64_cross_target_platformwin-64cro_h132010c2
    maxParallel: 7
  timeoutInMinutes: 360
  variables: {}

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
      export remote_url=$(Build.Repository.Uri)
      export sha=$(Build.SourceVersion)
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
      export CI=azure
      export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      export CONDA_BLD_DIR=/Users/runner/miniforge3/conda-bld
      export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
      # Archive everything in CONDA_BLD_DIR except environments
      export BLD_ARTIFACT_PREFIX=conda_artifacts
      if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
        # Archive the CONDA_BLD_DIR environments only when the job fails
        export ENV_ARTIFACT_PREFIX=conda_envs
      fi
      ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)
